name: Test

on:
  - push
  - pull_request

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:${{ matrix.postgresql-version }}
        env:
          POSTGRES_DB: pg_audit_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Python 3.13"
            python: "3.13"
            postgresql-version: 16
            tox: py13

          - name: "Python 3.12"
            python: "3.12"
            postgresql-version: 16
            tox: py12

          - name: "Python 3.11"
            python: "3.11"
            postgresql-version: 15
            tox: py11

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade tox setuptools

      - name: Run tests
        env:
          POSTGRESQL_AUDIT_TEST_PASSWORD: postgres
        run: tox -e ${{ matrix.tox }}
